// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGR93VvclQhaG3c5TYtpDKXzdVr0QY3Kg',
    appId: '1:159713230272:web:4b2f36f2fa7c73cbbadc25',
    messagingSenderId: '159713230272',
    projectId: 'cut-my-carbon',
    authDomain: 'cut-my-carbon.firebaseapp.com',
    storageBucket: 'cut-my-carbon.appspot.com',
    measurementId: 'G-9M0DDDZ71G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjhKaXzhizuSrvkcX2aixLWSQp_1rZTHU',
    appId: '1:159713230272:android:2e1e6484779fa7babadc25',
    messagingSenderId: '159713230272',
    projectId: 'cut-my-carbon',
    storageBucket: 'cut-my-carbon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn8dR8feLfAK6wvkyYkXEp1v4zqx7YgtU',
    appId: '1:159713230272:ios:c82c9a3d1a20545bbadc25',
    messagingSenderId: '159713230272',
    projectId: 'cut-my-carbon',
    storageBucket: 'cut-my-carbon.appspot.com',
    androidClientId: '159713230272-91jjlb570h6kgc9bl9hk57eke86d70cr.apps.googleusercontent.com',
    iosClientId: '159713230272-oe116663nto3tiblg76v88ka6rjfs0m1.apps.googleusercontent.com',
    iosBundleId: 'com.testing.cutMyCarbon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn8dR8feLfAK6wvkyYkXEp1v4zqx7YgtU',
    appId: '1:159713230272:ios:980cc4af80e00367badc25',
    messagingSenderId: '159713230272',
    projectId: 'cut-my-carbon',
    storageBucket: 'cut-my-carbon.appspot.com',
    androidClientId: '159713230272-91jjlb570h6kgc9bl9hk57eke86d70cr.apps.googleusercontent.com',
    iosClientId: '159713230272-k40b6s6opvdcl864s0g8qagf1bafbljf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cutMyCarbon',
  );
}
