// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf83oT9zzRt1mDdmJaoliVSSfJwLcUOv4',
    appId: '1:280514295082:web:193d71fff30df23e721a53',
    messagingSenderId: '280514295082',
    projectId: 'cut-my-carbon-c71bc',
    authDomain: 'cut-my-carbon-c71bc.firebaseapp.com',
    storageBucket: 'cut-my-carbon-c71bc.appspot.com',
    measurementId: 'G-2FH4NQX5B2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtSc3ipUe91bSwNs8NA-Hq3LNw95lya44',
    appId: '1:280514295082:android:971adee247d27570721a53',
    messagingSenderId: '280514295082',
    projectId: 'cut-my-carbon-c71bc',
    storageBucket: 'cut-my-carbon-c71bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXSSiJUwpm-7IJBlXgKD4vuZyjjRfQH1E',
    appId: '1:280514295082:ios:d0a7eb48639392ec721a53',
    messagingSenderId: '280514295082',
    projectId: 'cut-my-carbon-c71bc',
    storageBucket: 'cut-my-carbon-c71bc.appspot.com',
    iosClientId: '280514295082-t5og5u45f871lvmd5utp42u23vqdp3ve.apps.googleusercontent.com',
    iosBundleId: 'com.publishing.cutMyCarbon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXSSiJUwpm-7IJBlXgKD4vuZyjjRfQH1E',
    appId: '1:280514295082:ios:c8092113b3732c85721a53',
    messagingSenderId: '280514295082',
    projectId: 'cut-my-carbon-c71bc',
    storageBucket: 'cut-my-carbon-c71bc.appspot.com',
    iosClientId: '280514295082-c2lftecoq4ip05feahr0ic6nln3jidrd.apps.googleusercontent.com',
    iosBundleId: 'com.example.cutMyCarbon',
  );
}
